/**
 * Build script — run once to generate src/data/patternAreasBySize.js
 *
 * Usage:
 *   node scripts/generateAreasBySize.mjs
 *
 * Re-run whenever a pattern file changes or a new template is added.
 */

import {
  cisFemaleAdult32,
  cisFemaleAdult38,
  cisFemaleAdult44,
  cisMaleAdult36,
  cisMaleAdult42,
  cisMaleAdult48,
} from "@freesewing/models";
import { extractPatternPieces } from "../src/utils/extractFreeSewingPieces.js";
import { writeFileSync } from "fs";

// ── Add new patterns here (keep in sync with extractPatterns.mjs) ─────────────
import aaron from "../src/patterns/aaron.js";
import bella from "../src/patterns/bella.js";
import bent from "../src/patterns/bent.js";
import brian from "../src/patterns/brian.js";
import charlie from "../src/patterns/charlie.js";
import diana from "../src/patterns/diana.js";
import hortensia from "../src/patterns/hortensia.js";
import penelope from "../src/patterns/penelope.js";
import simon from "../src/patterns/simon.js";
import simone from "../src/patterns/simone.js";
import sophie from "../src/patterns/sophie.js";
import teagan from "../src/patterns/teagan.js";
import waralee from "../src/patterns/waralee.js";
import wahid from "../src/patterns/wahid.js";

const patternFiles = {
  aaron, bella, bent, brian, charlie, diana, hortensia,
  penelope, simon, simone, sophie, teagan, waralee, wahid,
};
// ─────────────────────────────────────────────────────────────────────────────

const anchors = {
  cisFemaleAdult32,
  cisFemaleAdult38,
  cisFemaleAdult44,
  cisMaleAdult36,
  cisMaleAdult42,
  cisMaleAdult48,
};

// Build ANCHOR_CHEST from the model objects at generation time.
const ANCHOR_CHEST = Object.fromEntries(
  Object.entries(anchors).map(([key, meas]) => [key, meas.chest]),
);

// ── Generate areas ─────────────────────────────────────────────────────────────
const patternAreas = {};
let templatesWritten = 0;

for (const [id, config] of Object.entries(patternFiles)) {
  const row = {};

  for (const [anchorKey, anchorMeasurements] of Object.entries(anchors)) {
    try {
      const mergedMeasurements = {
        ...config.measurements,
        ...anchorMeasurements, // anchor values win, same pattern as PatternLayoutScreen
      };
      const pieces = extractPatternPieces(
        config.Design,
        mergedMeasurements,
        config.parts,
      );
      const totalAreaCm2 = pieces.reduce((sum, p) => sum + (p.areaCm2 ?? 0), 0);
      row[anchorKey] = totalAreaCm2;
    } catch (err) {
      console.warn(`  ⚠  ${id} × ${anchorKey}: ${err.message} — recorded as null`);
      row[anchorKey] = null;
    }
  }

  console.log(
    `✓  ${id.padEnd(12)}` +
      Object.entries(row)
        .map(([k, v]) => `  ${k.replace("cis", "").replace("Adult", "")}=${v ?? "null"}`)
        .join(""),
  );
  patternAreas[id] = row;
  templatesWritten++;
}

// ── Serialise ──────────────────────────────────────────────────────────────────
const anchorChestLines = Object.entries(ANCHOR_CHEST)
  .map(([k, v]) => `  ${k.padEnd(20)}: ${v},`)
  .join("\n");

const templateLines = Object.entries(patternAreas)
  .map(([id, row]) => {
    const rowLines = Object.entries(row)
      .map(([k, v]) => `    ${k.padEnd(20)}: ${v ?? "null"},`)
      .join("\n");
    return `  ${id}: {\n${rowLines}\n  },`;
  })
  .join("\n");

const output = `// AUTO-GENERATED by scripts/generateAreasBySize.mjs — do not edit manually
// Re-run: node scripts/generateAreasBySize.mjs

export const ANCHOR_CHEST = {
${anchorChestLines}
};

export default {
${templateLines}
};
`;

writeFileSync("./src/data/patternAreasBySize.js", output);

console.log(`\nDone. ${templatesWritten} templates written.`);