/**
 * Pattern data for the Bucket Hat.
 * Loaded dynamically by PatternLayoutScreen and StepGuideScreen.
 */
export default {
  patternPieces: [
    // areaCm2 for trapezoid = (topWidth + bottomWidth) / 2 * height = (8+12)/2*14 = 140
    {
      id: "panel-1",
      label: "Crown Panel 1",
      widthCm: 12,
      heightCm: 14,
      areaCm2: 140,
      shape: "trapezoid",
      topWidthCm: 8,
      bottomWidthCm: 12,
      color: "#38bdf8",
      grainAngleDeg: 90,
      panel: "front",
      defaultX: 3,
      defaultY: 3,
    },
    {
      id: "panel-2",
      label: "Crown Panel 2",
      widthCm: 12,
      heightCm: 14,
      areaCm2: 140,
      shape: "trapezoid",
      topWidthCm: 8,
      bottomWidthCm: 12,
      color: "#38bdf8",
      grainAngleDeg: 90,
      panel: "front",
      defaultX: 3,
      defaultY: 28,
    },
    {
      id: "panel-3",
      label: "Crown Panel 3",
      widthCm: 12,
      heightCm: 14,
      areaCm2: 140,
      shape: "trapezoid",
      topWidthCm: 8,
      bottomWidthCm: 12,
      color: "#38bdf8",
      grainAngleDeg: 90,
      panel: "front",
      defaultX: 3,
      defaultY: 53,
    },
    {
      id: "panel-4",
      label: "Crown Panel 4",
      widthCm: 12,
      heightCm: 14,
      areaCm2: 140,
      shape: "trapezoid",
      topWidthCm: 8,
      bottomWidthCm: 12,
      color: "#0ea5e9",
      grainAngleDeg: 90,
      panel: "back",
      defaultX: 3,
      defaultY: 3,
    },
    {
      id: "panel-5",
      label: "Crown Panel 5",
      widthCm: 12,
      heightCm: 14,
      areaCm2: 140,
      shape: "trapezoid",
      topWidthCm: 8,
      bottomWidthCm: 12,
      color: "#0ea5e9",
      grainAngleDeg: 90,
      panel: "back",
      defaultX: 3,
      defaultY: 28,
    },
    {
      id: "panel-6",
      label: "Crown Panel 6",
      widthCm: 12,
      heightCm: 14,
      areaCm2: 140,
      shape: "trapezoid",
      topWidthCm: 8,
      bottomWidthCm: 12,
      color: "#0ea5e9",
      grainAngleDeg: 90,
      panel: "back",
      defaultX: 3,
      defaultY: 53,
    },
    // areaCm2 for circle = π * (14/2)² ≈ 154
    {
      id: "crown-top",
      label: "Crown Top",
      widthCm: 14,
      heightCm: 14,
      areaCm2: 154,
      shape: "circle",
      color: "#7dd3fc",
      grainAngleDeg: 0,
      panel: "front",
      defaultX: 55,
      defaultY: 3,
    },
    // areaCm2 for ring = π * (15² - 9²) ≈ 452
    {
      id: "brim",
      label: "Brim",
      widthCm: 30,
      heightCm: 30,
      areaCm2: 452,
      shape: "ring",
      outerRadiusCm: 15,
      innerRadiusCm: 9,
      color: "#bae6fd",
      grainAngleDeg: 0,
      panel: "back",
      defaultX: 5,
      defaultY: 15,
    },
  ],
  steps: [
    {
      title: "Prepare the Pattern",
      description:
        'Measure your head circumference (typically 56–58 cm for adults). Draw or download a bucket hat pattern with 1 cm seam allowance: 6 crown side panels (trapezoid), 1 crown top circle, and 1 brim ring. Search "bucket hat pattern PDF" to find a free printable.',
      tip: "Trace the pattern onto cardboard for a sturdier template that's easier to hold in place while cutting",
      duration: "20 min",
    },
    {
      title: "Cut the Fabric",
      description:
        "Trace the pattern pieces onto the fabric with a disappearing-ink marker and cut out: 6 crown side panels, 1 crown top circle, 2 brim rings (one for each side — use a contrasting fabric for a reversible look).",
      tip: "Align side panels along the straight grain of the fabric to prevent the hat from distorting",
      duration: "25 min",
    },
    {
      title: "Sew the Crown",
      description:
        "Sew the 6 side panels together in pairs (right sides facing), then join all pairs to form a cylindrical crown. Finally sew the circular top piece onto the crown, using pins every 3–4 cm around the curve.",
      tip: "Clip notches into the curved seam allowance after sewing so the seam lies flat when turned",
      duration: "30 min",
    },
    {
      title: "Make the Brim",
      description:
        "Place the two brim rings right sides together and sew around the outer curved edge. Clip notches every 1 cm around the curve, then turn right-side out and press flat. Leave the inner circle unsewn for now.",
      tip: "Clip notches to within 0.2 cm of the seam — not too close, or the seam may fray",
      duration: "25 min",
    },
    {
      title: "Attach Brim to Crown",
      description:
        "Align the open inner circle of the brim with the bottom edge of the crown (right sides facing). Pin every 3–4 cm around the full circumference, then stitch all the way around.",
      tip: "Do a quick hand-baste stitch first to check the fit before machine sewing",
      duration: "20 min",
    },
    {
      title: "Topstitch & Finish",
      description:
        "Press the seam allowance toward the crown. From the right side of the crown, topstitch ~0.2 cm from the seam to secure the seam allowance and add a clean finish. Optionally, topstitch around the outer brim edge for extra stiffness and style.",
      tip: "Slow down your machine speed on curves and gently guide the fabric for even stitching",
      duration: "15 min",
    },
  ],
};
